# Generated by Django 5.0.1 on 2024-02-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rules',
            field=models.BooleanField(default=False),
        ),
    ]
