# Generated by Django 5.0.1 on 2024-02-01 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0003_category_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField()),
                ('counts', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=60)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershop.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershop.country')),
            ],
        ),
    ]
